const url=import.meta.env.VITE_SUPABASE_URL;
const anon=import.meta.env.VITE_SUPABASE_ANON_KEY;
const SESSION_KEY='getir-arcade-session-v1';
export const backendAvailable=Boolean(url&&anon);
const session=()=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY))}catch{return null}};
const saveSession=value=>localStorage.setItem(SESSION_KEY,JSON.stringify(value));
async function accessToken(){
  const current=session();if(!current)return null;
  if((current.expires_at||0)>Date.now()/1000+60)return current.access_token;
  if(!current.refresh_token)return null;
  const response=await fetch(`${url}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{'Content-Type':'application/json',apikey:anon},body:JSON.stringify({refresh_token:current.refresh_token})});
  if(!response.ok){localStorage.removeItem(SESSION_KEY);return null}const refreshed=await response.json();saveSession(refreshed);return refreshed.access_token;
}
async function invoke(name,body,authenticated=false){if(!backendAvailable)throw new Error('Ortak lig henüz yapılandırılmadı. Misafir olarak oynayabilirsin.');const token=authenticated?await accessToken():anon;if(authenticated&&!token)throw new Error('Oturumun sona erdi. Lütfen tekrar giriş yap.');let response;try{response=await fetch(`${url}/functions/v1/${name}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:anon,Authorization:`Bearer ${token||anon}`},body:JSON.stringify(body)})}catch{throw new Error('Bağlantı kurulamadı. İlerlemen cihazında saklanıyor.')}const data=await response.json().catch(()=>({}));if(!response.ok){const suffix=data.requestId?` (Takip: ${String(data.requestId).slice(0,8)})`:'';const error=new Error(`${data.error||'İşlem tamamlanamadı'}${suffix}`);error.rejected=Boolean(data.rejected);error.requestId=data.requestId;throw error}return data;}
export async function register(nickname,password){const data=await invoke('register-with-nickname',{nickname,password});saveSession(data.session);return data;}
export async function login(nickname,password){const data=await invoke('login-with-nickname',{nickname,password});saveSession(data.session);return data;}
export function logout(){localStorage.removeItem(SESSION_KEY)}
export async function changePassword(password){return invoke('change-password',{password},true)}
export async function syncRuns(runs){const synced=[],rejected=[],results=[];for(const run of runs){try{const result=await invoke('submit-run',run,true);synced.push(run.clientRunId);results.push({clientRunId:run.clientRunId,status:result.status||(result.duplicate?'duplicate':'accepted')})}catch(error){if(error.rejected){synced.push(run.clientRunId);rejected.push(run.clientRunId);results.push({clientRunId:run.clientRunId,status:'rejected'})}else throw error}}return{synced,rejected,results};}
const tableFor=type=>type==='season'?'season_leaderboard':type==='getir-rush'?'rush_leaderboard':type==='televole-wars'?'televole_leaderboard':'depo_leaderboard';
export async function getLeaderboard(type='season',nickname=''){if(!backendAvailable)return[];const headers={apikey:anon,Authorization:`Bearer ${await accessToken()||anon}`},table=tableFor(type);const response=await fetch(`${url}/rest/v1/${table}?select=rank,nickname,${type==='season'?'xp':'score'}&order=rank.asc&limit=20`,{headers});if(!response.ok)throw new Error('Lig şu anda yüklenemiyor');const leaders=await response.json();if(nickname&&!leaders.some(row=>row.nickname===nickname)){const own=await fetch(`${url}/rest/v1/${table}?select=rank,nickname,${type==='season'?'xp':'score'}&nickname=eq.${encodeURIComponent(nickname)}&limit=1`,{headers});if(own.ok){const mine=(await own.json())[0];if(mine)leaders.push({...mine,is_current:true})}}return leaders;}
export async function getAccountData(){if(!backendAvailable)return null;const token=await accessToken();if(!token)return null;const headers={apikey:anon,Authorization:`Bearer ${token}`},fetchTable=async path=>{const response=await fetch(`${url}/rest/v1/${path}`,{headers});if(!response.ok)throw new Error('Hesap verileri alınamadı');return response.json()};const[profiles,runs,tasks,ledger]=await Promise.all([fetchTable('profiles?select=id,nickname,career_xp,total_score,total_runs,must_change_password'),fetchTable('runs?select=client_run_id,game_id,score,xp,duration_seconds,metrics,completed_at&order=completed_at.desc'),fetchTable('task_progress?select=period_key,task_id,value,rewarded'),fetchTable('xp_ledger?select=amount,source,source_key,created_at')]);return{profile:profiles[0],runs,tasks,ledger};}
