const STORE_KEY='getir-arcade-platform-v1';
export const DAILY_TASKS=[{id:'daily_play',title:'Isınma turu',description:'Herhangi bir oyun oyna',target:1,reward:100,metric:'runs'},{id:'daily_rush',title:'Teslimat zamanı',description:"Rush'ta 10 teslimat yap",target:10,reward:150,metric:'deliveries'},{id:'daily_depo',title:'Rafları hazırla',description:"Depo'da 3 raf temizle",target:3,reward:150,metric:'rowsCleared'}];
export const WEEKLY_TASKS=[{id:'weekly_runs',title:'Arcade müdavimi',description:'7 tur tamamla',target:7,reward:400,metric:'runs'},{id:'weekly_rush',title:'Haftanın kuryesi',description:'50 teslimat yap',target:50,reward:500,metric:'deliveries'},{id:'weekly_depo',title:'Depo ustası',description:'20 raf temizle',target:20,reward:500,metric:'rowsCleared'}];
const empty=()=>({version:1,profile:{mode:'guest',nickname:'Misafir'},runs:[],processedIds:[],careerXp:0,seasonXp:0,xpLedger:[],taskProgress:{},outbox:[],guestImported:false});
const safeParse=value=>{try{return JSON.parse(value)}catch{return null}};
export function dayKey(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);}
export function weekKey(date=new Date()){const local=new Date(date.toLocaleString('en-US',{timeZone:'Europe/Istanbul'}));const day=(local.getDay()+6)%7;local.setDate(local.getDate()-day);return dayKey(local);}
export function seasonKey(date=new Date()){return dayKey(date).slice(0,7);}
export function calculateRunXp(run){const score=Math.max(0,Number(run.score)||0),m=run.metrics||{};if(run.gameId==='getir-rush')return Math.min(400,50+(Number(m.deliveries)||0)*5+Math.floor(score/100));if(run.gameId==='depo-tetris')return Math.min(400,50+(Number(m.rowsCleared)||0)*15+Math.floor(score/100));return Math.min(400,50+Math.floor(score/100));}
export function levelForXp(xp){return 1+Math.floor(Math.max(0,xp)/1000)}
export function normalizeRun(input){if(!input||!['getir-rush','depo-tetris'].includes(input.gameId))throw new Error('Geçersiz oyun sonucu');return{clientRunId:String(input.clientRunId||globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`),gameId:input.gameId,score:Math.max(0,Math.round(Number(input.score)||0)),durationSeconds:Math.max(0,Math.round(Number(input.durationSeconds)||0)),completedAt:input.completedAt||new Date().toISOString(),metrics:input.metrics||{}};}
function progressTask(state,task,period,value){const key=`${period}:${task.id}`,entry=state.taskProgress[key]||{value:0,completed:false,rewarded:false};entry.value=Math.min(task.target,entry.value+value);entry.completed=entry.value>=task.target;if(entry.completed&&!entry.rewarded){entry.rewarded=true;state.careerXp+=task.reward;state.seasonXp+=task.reward;state.xpLedger.push({id:`task:${key}`,amount:task.reward,source:task.id,createdAt:new Date().toISOString()});}state.taskProgress[key]=entry;}
function applyTasks(state,run){const daily=dayKey(new Date(run.completedAt)),weekly=weekKey(new Date(run.completedAt)),deliveries=run.gameId==='getir-rush'?Number(run.metrics.deliveries)||0:0,rows=run.gameId==='depo-tetris'?Number(run.metrics.rowsCleared)||0:0;for(const task of DAILY_TASKS)progressTask(state,task,daily,task.metric==='runs'?1:task.metric==='deliveries'?deliveries:rows);for(const task of WEEKLY_TASKS)progressTask(state,task,weekly,task.metric==='runs'?1:task.metric==='deliveries'?deliveries:rows);}
export function createArcadeStore(storage=globalThis.localStorage){
  let state=safeParse(storage?.getItem(STORE_KEY))||empty();
  const save=()=>{storage?.setItem(STORE_KEY,JSON.stringify(state));globalThis.dispatchEvent?.(new CustomEvent('arcade:updated',{detail:getSnapshot()}));};
  const getSnapshot=()=>{const runs=[...state.runs].sort((a,b)=>new Date(b.completedAt)-new Date(a.completedAt)),stats={};for(const gameId of['getir-rush','depo-tetris']){const list=runs.filter(r=>r.gameId===gameId);stats[gameId]={plays:list.length,bestScore:Math.max(0,...list.map(r=>r.score)),lastScore:list[0]?.score||0,lastPlayed:list[0]?.completedAt||null,totalScore:list.reduce((s,r)=>s+r.score,0)};}return{...state,runs,totalScore:runs.reduce((s,r)=>s+r.score,0),totalRuns:runs.length,level:levelForXp(state.careerXp),gameStats:stats,dailyTasks:DAILY_TASKS.map(t=>({...t,...(state.taskProgress[`${dayKey()}:${t.id}`]||{value:0,completed:false,rewarded:false})})),weeklyTasks:WEEKLY_TASKS.map(t=>({...t,...(state.taskProgress[`${weekKey()}:${t.id}`]||{value:0,completed:false,rewarded:false})}))};};
  return{
    getSnapshot,
    recordRun(input){const run=normalizeRun(input);if(state.processedIds.includes(run.clientRunId))return getSnapshot();const xp=calculateRunXp(run),record={...run,xp};state.processedIds.push(run.clientRunId);state.runs.push(record);state.careerXp+=xp;state.seasonXp+=xp;state.xpLedger.push({id:`run:${run.clientRunId}`,amount:xp,source:run.gameId,createdAt:run.completedAt});applyTasks(state,run);if(state.profile.mode==='account')state.outbox.push(record);save();return getSnapshot();},
    setAccount(profile){state.profile={mode:'account',nickname:profile.nickname,userId:profile.userId};if(!state.guestImported){state.outbox=[...state.runs];state.guestImported=true;}save();},
    mergeRemote(remote){const mapped=(remote.runs||[]).map(r=>({clientRunId:r.client_run_id,gameId:r.game_id,score:r.score,xp:r.xp,durationSeconds:r.duration_seconds,metrics:r.metrics||{},completedAt:r.completed_at})),byId=new Map([...state.runs,...mapped].map(r=>[r.clientRunId,r]));state.runs=[...byId.values()];state.processedIds=[...new Set([...state.processedIds,...mapped.map(r=>r.clientRunId)])];if(remote.profile){state.profile={mode:'account',nickname:remote.profile.nickname,userId:remote.profile.id};state.careerXp=remote.profile.career_xp||0;}if(remote.ledger){state.xpLedger=remote.ledger.map(x=>({id:x.source_key,amount:x.amount,source:x.source,createdAt:x.created_at}));const current=seasonKey();state.seasonXp=state.xpLedger.filter(x=>x.createdAt?.slice(0,7)===current).reduce((sum,x)=>sum+x.amount,0);}for(const t of remote.tasks||[])state.taskProgress[`${t.period_key}:${t.task_id}`]={value:t.value,completed:t.rewarded,rewarded:t.rewarded};save();},
    setGuest(){state.profile={mode:'guest',nickname:'Misafir'};save();},
    markSynced(ids){state.outbox=state.outbox.filter(r=>!ids.includes(r.clientRunId));save();},
    clearSession(){state.profile={mode:'guest',nickname:'Misafir'};save();},
    reset(){state=empty();save();}
  };
}
export const arcadeStore=typeof window!=='undefined'?createArcadeStore(window.localStorage):null;
