import test from 'node:test';import assert from 'node:assert/strict';import{calculateRunXp,createArcadeStore,levelForXp,normalizeRun}from'./store.js';
const memory=()=>{let value=null;return{getItem:()=>value,setItem:(_,v)=>value=v}};
test('xp is normalized per game and capped',()=>{assert.equal(calculateRunXp({gameId:'getir-rush',score:1000,metrics:{deliveries:10}}),110);assert.equal(calculateRunXp({gameId:'depo-tetris',score:1000,metrics:{rowsCleared:3}}),105);assert.equal(calculateRunXp({gameId:'depo-tetris',score:999999,metrics:{rowsCleared:99}}),400)});
test('duplicate run is idempotent',()=>{const store=createArcadeStore(memory()),run=normalizeRun({clientRunId:'one',gameId:'getir-rush',score:100,durationSeconds:180,metrics:{deliveries:2}});store.recordRun(run);store.recordRun(run);assert.equal(store.getSnapshot().totalRuns,1)});
test('tasks and levels progress from runs',()=>{const store=createArcadeStore(memory());store.recordRun({clientRunId:'two',gameId:'getir-rush',score:100,durationSeconds:180,metrics:{deliveries:10}});const s=store.getSnapshot();assert.equal(s.dailyTasks[0].completed,true);assert.equal(s.dailyTasks[1].completed,true);assert.equal(s.careerXp,351);assert.equal(levelForXp(2000),3)});
test('guest runs enter the outbox once after account creation',()=>{const store=createArcadeStore(memory());store.recordRun({clientRunId:'guest',gameId:'depo-tetris',score:500,durationSeconds:180,metrics:{rowsCleared:2}});store.setAccount({nickname:'oyuncu',userId:'u1'});assert.equal(store.getSnapshot().outbox.length,1);store.markSynced(['guest']);store.setAccount({nickname:'oyuncu',userId:'u1'});assert.equal(store.getSnapshot().outbox.length,0)});
test('pending runs cannot leak into another account',()=>{const store=createArcadeStore(memory());store.recordRun({clientRunId:'guest-run',gameId:'depo-tetris',score:500,durationSeconds:180,metrics:{rowsCleared:2}});store.setAccount({nickname:'bir',userId:'u1'});store.recordRun({clientRunId:'account-run',gameId:'getir-rush',score:200,durationSeconds:180,metrics:{deliveries:1}});store.setAccount({nickname:'iki',userId:'u2'});assert.equal(store.getSnapshot().outbox.length,0);assert.equal(store.getSnapshot().outboxOwnerId,'u2')});
test('sync failures keep the outbox for a retry',()=>{const store=createArcadeStore(memory());store.setAccount({nickname:'oyuncu',userId:'u1'});store.recordRun({clientRunId:'retry-run',gameId:'getir-rush',score:100,durationSeconds:180,metrics:{deliveries:1}});store.markSyncFailed('çevrimdışı');assert.equal(store.getSnapshot().outbox.length,1);assert.equal(store.getSnapshot().sync.status,'error')});
test('televole runs receive headline xp and appear in stats',()=>{const store=createArcadeStore(memory());store.recordRun({clientRunId:'televole-run',gameId:'televole-wars',score:1000,durationSeconds:90,metrics:{headlines:10}});const s=store.getSnapshot();assert.equal(s.gameStats['televole-wars'].bestScore,1000);assert.equal(s.careerXp,190)});
