import { RUN_DURATION, PERKS, calculateDeliveryScore, difficultyAt, samplePerks } from "./core.js";

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const rnd=(a,b)=>a+Math.random()*(b-a);

export class RushGame {
  constructor(canvas, events={}) {
    this.canvas=canvas; this.ctx=canvas.getContext("2d"); this.events=events; this.keys=new Set();
    this.ctx.imageSmoothingEnabled=false;
    addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","w","a","s","d","W","A","S","D"].includes(e.key))e.preventDefault();this.keys.add(e.key.toLowerCase());});
    addEventListener("keyup",e=>this.keys.delete(e.key.toLowerCase()));
    this.resizeObserver=new ResizeObserver(()=>this.resize()); this.resizeObserver.observe(canvas); this.resize(); this.drawBackdrop();
  }
  resize(){const r=this.canvas.getBoundingClientRect();const d=Math.min(devicePixelRatio,2);if(r.width&&this.canvas.width!==r.width*d){this.canvas.width=r.width*d;this.canvas.height=r.width*.625*d;this.ctx.setTransform(d,0,0,d,0,0);this.ctx.imageSmoothingEnabled=false;this.w=r.width;this.h=r.width*.625;}}
  start(){this.running=true;this.paused=false;this.elapsed=0;this.score=0;this.deliveries=0;this.xp=0;this.level=1;this.nextXp=3;this.spawnClock=0;this.orderClock=0;this.rushAnnounced=false;this.last=performance.now();this.hazards=[];this.drops=[];this.particles=[];this.perks=[];this.stats={speed:210,pickup:42,shield:0,combo:0,armor:0,distance:0,magnet:0,maxHealth:100,health:100,score:0,slow:0};this.player={x:this.w/2,y:this.h/2,dir:1,moving:false};this.order=this.makeOrder();this.target=null;this.events.sound?.("start");this.loop(this.last);this.emit();}
  makeOrder(){return{x:rnd(65,this.w-65),y:rnd(95,this.h-65)};}
  makeTarget(){let p;do{p=this.makeOrder()}while(dist(p,this.player)<180*(1-this.stats.distance));p.customers=1+Math.floor(Math.random()*3);p.style=Math.floor(Math.random()*4);return p;}
  pauseForPerk(){this.paused=true;this.events.sound?.("perkOpen");this.events.perk?.(samplePerks(PERKS));}
  choosePerk(perk){this.events.sound?.("perkChoose");this.perks.push(perk);const s=this.stats;if(perk.stat==="speed")s.speed*=1+perk.amount;if(perk.stat==="pickup")s.pickup*=1+perk.amount;if(perk.stat==="coffee"){s.speed*=1.1;s.pickup*=1.1}else if(perk.stat==="heal")s.health=Math.min(s.maxHealth,s.health+perk.amount);else if(perk.stat==="maxHealth"){s.maxHealth+=perk.amount;s.health+=perk.amount}else if(!["speed","pickup"].includes(perk.stat))s[perk.stat]=(s[perk.stat]||0)+perk.amount;this.paused=false;this.last=performance.now();this.events.perkChosen?.(this.perks);}
  update(dt){if(this.paused||!this.running)return;this.elapsed+=dt;const d=difficultyAt(this.elapsed);let dx=(this.keys.has("d")||this.keys.has("arrowright")?1:0)-(this.keys.has("a")||this.keys.has("arrowleft")?1:0);let dy=(this.keys.has("s")||this.keys.has("arrowdown")?1:0)-(this.keys.has("w")||this.keys.has("arrowup")?1:0);const len=Math.hypot(dx,dy)||1;this.player.moving=!!(dx||dy);if(dx)this.player.dir=Math.sign(dx);this.player.x=clamp(this.player.x+dx/len*this.stats.speed*dt,24,this.w-24);this.player.y=clamp(this.player.y+dy/len*this.stats.speed*dt,78,this.h-24);
    this.spawnClock+=dt;if(this.spawnClock>d.spawnEvery){this.spawnClock=0;this.spawnHazard(d);}
    if(d.rush&&!this.rushAnnounced){this.rushAnnounced=true;this.events.sound?.("rush");}
    for(const h of this.hazards){h.x+=h.vx*dt*(1-this.stats.slow);h.y+=h.vy*dt*(1-this.stats.slow);h.hit=Math.max(0,h.hit-dt);if(!h.hit&&dist(h,this.player)<h.r+15){h.hit=.8;if(this.stats.shield>=1){this.stats.shield-=1;this.events.sound?.("shield");this.burst(this.player.x,this.player.y,"#ffd300")}else{this.stats.health-=Math.round(h.damage*(1-this.stats.armor));this.events.sound?.("hit");this.burst(this.player.x,this.player.y,"#ff5b70");}}}
    this.hazards=this.hazards.filter(h=>h.x>-100&&h.x<this.w+100&&h.y>-100&&h.y<this.h+100);
    if(this.order&&!this.target){if(this.stats.magnet&&dist(this.order,this.player)<170){this.order.x+=(this.player.x-this.order.x)*dt*2;this.order.y+=(this.player.y-this.order.y)*dt*2;}if(dist(this.order,this.player)<this.stats.pickup){this.target=this.makeTarget();this.order=null;this.events.sound?.("pickup");this.burst(this.player.x,this.player.y,"#ffd300");}}
    if(this.target&&dist(this.target,this.player)<48){this.deliveries++;this.score+=calculateDeliveryScore(this.deliveries,this.stats);this.xp++;this.target=null;this.order=this.makeOrder();this.events.sound?.("delivery");this.burst(this.player.x,this.player.y,"#6bd38d");if(this.xp>=this.nextXp){this.level++;this.xp=0;this.nextXp=Math.min(7,this.nextXp+1);this.pauseForPerk();}}
    this.score+=dt*2;for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}this.particles=this.particles.filter(p=>p.life>0);
    if(this.stats.health<=0)this.end("energy");else if(this.elapsed>=RUN_DURATION)this.end("complete");this.emit(d);
  }
  spawnHazard(d){const side=Math.floor(Math.random()*4);let x,y,vx,vy;const speed=d.speed*rnd(.8,1.25);if(side<2){x=side?this.w+40:-40;y=rnd(90,this.h-30);vx=side?-speed:speed;vy=rnd(-20,20)}else{x=rnd(30,this.w-30);y=side===2?-40:this.h+40;vx=rnd(-20,20);vy=side===2?speed:-speed}const rain=Math.random()<.28;this.hazards.push({x,y,vx,vy,r:rain?12:20,damage:rain?8:15,type:rain?"rain":"car",hit:0});}
  burst(x,y,color){for(let i=0;i<10;i++)this.particles.push({x,y,vx:rnd(-100,100),vy:rnd(-100,100),life:rnd(.3,.7),color});}
  emit(d=difficultyAt(this.elapsed)){this.events.update?.({time:RUN_DURATION-this.elapsed,score:Math.floor(this.score),deliveries:this.deliveries,health:this.stats.health/this.stats.maxHealth,wave:d.wave,rush:d.rush});}
  end(reason){if(!this.running)return;this.running=false;this.events.sound?.(reason==="complete"?"complete":"energy");this.events.end?.({score:Math.floor(this.score),deliveries:this.deliveries,time:Math.min(this.elapsed,RUN_DURATION),perks:this.perks,reason,seed:Date.now()});}
  loop(now){if(!this.running)return;const dt=Math.min(.033,(now-this.last)/1000);this.last=now;this.update(dt);this.draw();requestAnimationFrame(t=>this.loop(t));}
  rounded(x,y,w,h,r,color){const c=this.ctx;c.fillStyle=color;c.beginPath();c.roundRect(x,y,w,h,r);c.fill();}
  pixel(x,y,w,h,color){this.ctx.fillStyle=color;this.ctx.fillRect(Math.round(x),Math.round(y),w,h);}
  drawTree(x,y){this.pixel(x-3,y+8,6,12,"#65452f");this.pixel(x-12,y-2,24,13,"#367c57");this.pixel(x-8,y-8,16,8,"#55a76e");this.pixel(x-4,y-12,8,5,"#79c47f");}
  drawBuilding(x,y,w,h,index){const colors=["#e5b96d","#d58d80","#ad92c8","#86b6b1"];this.pixel(x+4,y+5,w,h,"#745a79");this.pixel(x,y,w,h,colors[index%colors.length]);this.pixel(x-3,y,w+6,6,"#f5d988");for(let wy=y+13;wy<y+h-9;wy+=18)for(let wx=x+10;wx<x+w-8;wx+=20){this.pixel(wx,wy,9,10,"#493f68");this.pixel(wx+2,wy+2,5,4,"#9bd2d0");}this.pixel(x+w/2-7,y+h-14,14,14,"#684861");}
  drawBackdrop(){if(!this.ctx)return;const c=this.ctx,w=this.w||960,h=this.h||600;c.imageSmoothingEnabled=false;this.pixel(0,0,w,h,"#b9a4ca");
    for(let y=65;y<h;y+=130){this.pixel(0,y-28,w,56,"#5c566b");this.pixel(0,y-32,w,4,"#ded4e4");this.pixel(0,y+28,w,4,"#8c799c");for(let x=12;x<w;x+=54)this.pixel(x,y-2,28,4,"#e8d875");for(let x=24;x<w;x+=160){for(let i=0;i<5;i++)this.pixel(x+i*9,y-27,5,15,"#eee8f2");}}
    for(let x=115;x<w;x+=230){this.pixel(x-25,0,50,h,"#5c566b");this.pixel(x-29,0,4,h,"#ded4e4");this.pixel(x+25,0,4,h,"#8c799c");for(let y=15;y<h;y+=58)this.pixel(x-2,y,4,30,"#e8d875");}
    for(let row=0,y=4;y<h;y+=130,row++)for(let col=0,x=4;x<w;x+=150,col++){if((x>80&&x<155)||(x>310&&x<385)||(x>540&&x<615)||(x>770&&x<845))continue;this.drawBuilding(x,y,92,52,(row+col)%4);if((row+col)%2)this.drawTree(x+112,y+27);}
    c.globalAlpha=.2;for(let x=0;x<w;x+=16)for(let y=0;y<h;y+=16)if((x+y)%48===0)this.pixel(x,y,3,3,"#ffffff");c.globalAlpha=1;
  }
  drawCourier(){const c=this.ctx,p=this.player,bob=p.moving?Math.floor(this.elapsed*12)%2:0,wheel=Math.floor(this.elapsed*18)%2;c.save();c.translate(Math.round(p.x),Math.round(p.y+bob));c.scale(p.dir,1);
    this.pixel(-17,10,10,10,"#241a30");this.pixel(12,10,10,10,"#241a30");this.pixel(-15,12,6,6,wheel?"#9c8baa":"#665873");this.pixel(14,12,6,6,wheel?"#665873":"#9c8baa");
    this.pixel(-18,4,35,10,"#5d2d91");this.pixel(-12,-1,25,8,"#7240a2");this.pixel(10,-7,7,14,"#ffd300");this.pixel(15,-10,5,4,"#fff2a8");this.pixel(-6,5,10,4,"#ffd300");
    this.pixel(-18,-7,9,15,"#ffd300");this.pixel(-21,-10,12,5,"#5d2d91");this.pixel(-16,-3,5,5,"#5d2d91");
    this.pixel(-7,-10,15,13,"#5d2d91");this.pixel(-4,-17,12,9,"#e2a476");this.pixel(-6,-22,15,6,"#ffd300");this.pixel(-3,-24,9,3,"#6f3aa0");this.pixel(5,-15,3,3,"#241238");
    this.pixel(6,-5,11,5,"#e2a476");this.pixel(14,-7,4,8,"#5d2d91");this.pixel(-5,0,14,5,"#39234e");
    c.restore();}
  drawCar(h){const c=this.ctx,angle=Math.atan2(h.vy,h.vx);c.save();c.translate(Math.round(h.x),Math.round(h.y));c.rotate(angle);const body=h.hit?"#ff8394":"#6a3197";this.pixel(-23,-13,46,26,"#342543");this.pixel(-19,-16,31,32,body);this.pixel(-10,-13,16,26,"#89c5d0");this.pixel(-7,-10,10,20,"#bde1dd");this.pixel(-24,-10,6,7,"#ffd86a");this.pixel(-24,4,6,7,"#ffd86a");this.pixel(17,-11,7,7,"#ff6072");this.pixel(17,4,7,7,"#ff6072");this.pixel(-14,-19,9,4,"#242031");this.pixel(7,-19,9,4,"#242031");this.pixel(-14,15,9,4,"#242031");this.pixel(7,15,9,4,"#242031");c.restore();}
  drawPackage(p){const c=this.ctx,bob=Math.sin(this.elapsed*5)*3,sway=Math.sin(this.elapsed*3)*.08,pulse=.55+Math.sin(this.elapsed*6)*.16;c.save();c.translate(Math.round(p.x),Math.round(p.y+bob));c.fillStyle=`rgba(255,211,0,${pulse})`;c.beginPath();c.arc(0,2,23+Math.sin(this.elapsed*6)*2,0,Math.PI*2);c.fill();c.rotate(sway);this.pixel(-15,-8,30,24,"#47209a");this.pixel(-15,-8,30,5,"#6f3ed1");this.pixel(-15,11,30,5,"#301474");this.pixel(-11,-16,5,10,"#5e30bd");this.pixel(6,-16,5,10,"#5e30bd");this.pixel(-8,-20,16,5,"#5e30bd");this.pixel(-12,-5,24,3,"#7650d7");this.pixel(-10,3,20,8,"#ffd300");c.fillStyle="#47209a";c.font="900 9px system-ui";c.textAlign="center";c.fillText("g!",0,10);this.pixel(11,-5,4,16,"#35147e");c.restore();}
  drawCustomer(x,y,style,index){const skins=["#e3a778","#8f5d45","#f1c39d","#b97855"],shirts=["#54a879","#d66776","#6b55a4","#4e8fb2"],skin=skins[(style+index)%skins.length],shirt=shirts[(style+index*2)%shirts.length];this.pixel(x-5,y-15,10,10,skin);this.pixel(x-6,y-18,12,5,(style+index)%2?"#35253e":"#704536");this.pixel(x-7,y-5,14,14,shirt);this.pixel(x-6,y+9,5,8,"#392f48");this.pixel(x+2,y+9,5,8,"#392f48");this.pixel(x-10,y-3,4,9,skin);this.pixel(x+7,y-3,4,9,skin);this.pixel(x+2,y-11,2,2,"#241238");}
  drawCustomers(p){const c=this.ctx,count=p.customers||1,spacing=16,start=-(count-1)*spacing/2;c.save();c.translate(Math.round(p.x),Math.round(p.y));this.pixel(-25,18,50,4,"#4c3c5a55");for(let i=0;i<count;i++){c.save();c.translate(0,Math.sin(this.elapsed*3+i*1.7)*1.5);this.drawCustomer(start+i*spacing,0,p.style||0,i);c.restore();}c.restore();}
  draw(){const c=this.ctx;this.drawBackdrop();if(this.elapsed>=150){c.fillStyle=`rgba(255,80,70,${.06+Math.sin(this.elapsed*5)*.025})`;c.fillRect(0,0,this.w,this.h);c.fillStyle="#ffdc4d";c.font="900 14px system-ui";c.fillText("⚡ SON DALGA: RUSH!",this.w/2-75,80)}
    if(this.order)this.drawPackage(this.order);if(this.target){const pulse=(this.elapsed*1.8)%1;c.fillStyle="#28e88955";c.beginPath();c.ellipse(this.target.x,this.target.y+18,31+Math.sin(this.elapsed*4)*3,13,0,0,Math.PI*2);c.fill();c.strokeStyle=`rgba(55,255,151,${1-pulse})`;c.lineWidth=3;c.beginPath();c.ellipse(this.target.x,this.target.y+18,29+pulse*18,12+pulse*8,0,0,Math.PI*2);c.stroke();c.strokeStyle="#9affc8";c.lineWidth=2;c.beginPath();c.ellipse(this.target.x,this.target.y+18,27,11,0,0,Math.PI*2);c.stroke();this.drawCustomers(this.target);c.strokeStyle="#53ffa088";c.lineWidth=2;c.setLineDash([6,7]);c.beginPath();c.moveTo(this.player.x,this.player.y);c.lineTo(this.target.x,this.target.y);c.stroke();c.setLineDash([]);c.lineWidth=1;}
    for(const h of this.hazards){if(h.type==="car")this.drawCar(h);else{c.save();c.translate(Math.round(h.x),Math.round(h.y));this.pixel(-3,-15,6,8,"#b8e4ee");this.pixel(-8,-7,16,7,"#65a9d6");this.pixel(-11,0,22,7,"#4c8dc2");this.pixel(-7,7,14,7,"#3674aa");c.restore()}}
    for(const p of this.particles){c.globalAlpha=p.life*2;c.fillStyle=p.color;c.fillRect(Math.round(p.x),Math.round(p.y),5,5)}c.globalAlpha=1;this.drawCourier();if(this.stats.shield){c.strokeStyle="#ffd300";c.lineWidth=4;c.setLineDash([5,3]);c.beginPath();c.arc(this.player.x,this.player.y,27,0,Math.PI*2);c.stroke();c.setLineDash([])}c.textAlign="left";
  }
}
